version: '3.7'

services:
  mancala:
    image: mancala
    build:
      context: .
    container_name: mancala
    ports:
      - 8080:8080
    networks:
      - cycleon
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mancala
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
      - 5432:5432
    networks:
      - cycleon
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mancala
      - PGDATA=/data/postgres
    volumes:
      - postgre_data:/data/postgres
networks:
  cycleon:
    driver: bridge
volumes:
  postgre_data: